# See https://docs.minecraftforge.net/en/1.21.x/gettingstarted/modfiles/#modstoml
# There are lots of things you can do with the mods.toml, and not all fields are included with this MDK
# References: https://github.com/MinecraftForge/MDKExamples

modLoader="javafml"
loaderVersion="[65,)"
license="All Rights Reserved"

[[mods]]
modId="xpmagic"
version="1.0.1"
displayName="XPMagic"
authors="GatheredSatyr53"
credits="Created by GatheredSatyr53"

description='''Store, refine, and reclaim experience. Bottle your XP through a keeper machine,
separate memory powder into fractions and mix it back, fuse it into crystals with explosions and
lightning, transform them in soul fire, and carve crystal tools.'''

[[dependencies.xpmagic]] #recommended
    modId="forge"
    mandatory=true
    versionRange="[65,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.xpmagic]] #recommended
    modId="minecraft"
    mandatory=true
    versionRange="[26.2,26.3,)"
    ordering="NONE"
    side="BOTH"
