# See https://docs.neoforged.net/docs/gettingstarted/modfiles/#neoforgemodstoml
# There are lots of things you can do with the neoforge.mods.toml, and not all fields are included with this MDK

modLoader="javafml"
loaderVersion="[1,)"
license="All Rights Reserved"
issueTrackerURL="https://github.com/GatheredSatyr53/XPMagic/issues"

[[mods]]
modId="xpmagic"
version="1.0.4"
displayName="XPMagic"
displayURL="https://github.com/GatheredSatyr53/XPMagic"
authors="GatheredSatyr53"
credits="Created by GatheredSatyr53"

description='''Store, refine, and reclaim experience. Bottle your XP through a keeper machine,
separate memory powder into fractions and mix it back, fuse it into crystals with explosions and
lightning, transform them in soul fire, and carve crystal tools.'''

[[dependencies.xpmagic]]
    modId="neoforge"
    type="required"
    versionRange="[26.2,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.xpmagic]]
    modId="minecraft"
    type="required"
    versionRange="[26.2,26.3)"
    ordering="NONE"
    side="BOTH"
